global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using AutoMapper;
global using DofyEcom.Helper;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
