export interface IContactUsConfigModel {
    id: number,
    validationErrors: {},
    Name: string,
    EnumName: string,
    WhatsAppPhone:string,
    BuyPhone: string,
    OrderPhone: string,
    Address: string,
    BuyEmail: string,
    OrderEmail: string,
    BusinessEmail: string,
    FaceBookLink: string,
    InstagramLink: string,
    LinkedInLink: string,
    TikTokLink: string,
    YouTubeLink: string,
    TwitterLink: string,
    Published: boolean,
    CreatedOnUtc: any,
    UpdatedOnUtc: any,
}