export interface ICorporateTradeInModel {
    id: number,
    created: any,
    createdBy: number,
    active: true,
    modified: any,
    modifiedBy: number,
    validationErrors: {},
    name: string,
    mobile: string,
    SecondaryMobile:string,
    email: string,
    description: string,
    subject: string,
    state: any,
    district: any,
    ContactUsCode: string,
    CorporateTradeInCode: string,
    pincode: string,
}