export interface IDOFYGeoModel {
    Id: number,
    Created: any,
    CreatedBy: number,
    Active: boolean,
    Modified: any,
    ModifiedBy: number,
    EnumName: string,
    DeliveryDelay: number,
    DisplayInList: boolean,
    Identifier: number,
    IsValid: boolean,
    Level: number,
    LevelName: string,
    Name: string,
    Parent: number,
    Parent1: any,
    RowOrder: number,
    SecondLanguage: string,
    ClusterId: number,
    Code: string,
    CutoffTime: string,
    DayCount?: string,
    DisplayGeoName?: string,
    EncryptedId: any,
    EncryptedIdentifier: any,
    EncryptedParent: any,
}


