import React from "react";

const BrandLogo = [
  { logo: "/assets/BrandImages/ABBA.png", alt: "ABBA" },
  { logo: "/assets/BrandImages/ABRO.jpg", alt: "ABRO" },
  { logo: "/assets/BrandImages/AMAANDO.png", alt: "AMAANDO" },
  { logo: "/assets/BrandImages/APZ.png", alt: "APZ" },
  { logo: "/assets/BrandImages/ARGO.png", alt: "ARGO" },
  { logo: "/assets/BrandImages/ARP.png", alt: "ARP" },
  { logo: "/assets/BrandImages/ART.png", alt: "ART" },
  { logo: "/assets/BrandImages/ASAHI.png", alt: "ASAHI" },
  { logo: "/assets/BrandImages/ASTON.png", alt: "ASTON" },
  { logo: "/assets/BrandImages/BBCR.png", alt: "BBCR" },
  { logo: "/assets/BrandImages/BEA.jpg", alt: "BEA" },
  { logo: "/assets/BrandImages/BECO.png", alt: "BECO" },
  { logo: "/assets/BrandImages/BECOOL.jpg", alt: "BECOOL" },
  { logo: "/assets/BrandImages/BELIEF.png", alt: "BELIEF" },
  { logo: "/assets/BrandImages/BMZ.png", alt: "BMZ" },
  { logo: "/assets/BrandImages/BONDLOC.png", alt: "BONDLOC" },
  { logo: "/assets/BrandImages/BS BEARING.jpg", alt: "BS BEARING" },
  { logo: "/assets/BrandImages/BSN.png", alt: "BSN" },
  { logo: "/assets/BrandImages/BW.png", alt: "BW" },
  { logo: "/assets/BrandImages/CAMOZZI.png", alt: "CAMOZZI" },
  { logo: "/assets/BrandImages/CHIARAVALLI.png", alt: "CHIARAVALLI" },
  { logo: "/assets/BrandImages/CHOCHO.png", alt: "CHOHO" },
  { logo: "/assets/BrandImages/CONTITECH.jpg", alt: "CONTITECH" },
  { logo: "/assets/BrandImages/COOPER.png", alt: "COOPER" },
  { logo: "/assets/BrandImages/COPELAND.jpg", alt: "COPELAND" },
  { logo: "/assets/BrandImages/CRAFT BEARINGS.png", alt: "CRAFT BEARINGS" },
  { logo: "/assets/BrandImages/CSB.png", alt: "CSB" },
  { logo: "/assets/BrandImages/CSHBELT.png", alt: "CSHBELT" },
  { logo: "/assets/BrandImages/CTS.png", alt: "CTS" },
  { logo: "/assets/BrandImages/CX.png", alt: "CX" },
  { logo: "/assets/BrandImages/CZH.gif", alt: "CZH BEARING" },
  { logo: "/assets/BrandImages/DESCH.png", alt: "DESCH" },
  { logo: "/assets/BrandImages/DETOOL.png", alt: "DETOOL" },
  { logo: "/assets/BrandImages/DICHTOMATIK.png", alt: "DICHTOMATIK" },
  { logo: "/assets/BrandImages/DINROLL.png", alt: "DINROLL" },
  { logo: "/assets/BrandImages/DONGHUA.png", alt: "DONGHUA" },
  { logo: "/assets/BrandImages/DPN.png", alt: "DPN" },
  { logo: "/assets/BrandImages/DURBAL.png", alt: "DURBAL" },
  { logo: "/assets/BrandImages/DXP.png", alt: "DXP" },
  { logo: "/assets/BrandImages/DYZ.png", alt: "DYZ" },
  { logo: "/assets/BrandImages/EDGE.png", alt: "EDGE" },
  { logo: "/assets/BrandImages/ELATECH.png", alt: "ELATECH" },
  { logo: "/assets/BrandImages/EWELLIX.png", alt: "EWELLIX" },
  { logo: "/assets/BrandImages/EZO.png", alt: "EZO" },
  { logo: "/assets/BrandImages/FAG.png", alt: "FAG" },
  { logo: "/assets/BrandImages/FBC.png", alt: "FBC" },
  { logo: "/assets/BrandImages/FBJ.png", alt: "FBJ" },
  { logo: "/assets/BrandImages/FEKEN.png", alt: "FEIKEN" },
  { logo: "/assets/BrandImages/FENNER.png", alt: "FENNER" },
  { logo: "/assets/BrandImages/FERSA.png", alt: "FERSA" },
  { logo: "/assets/BrandImages/FHY.png", alt: "FHY" },
  { logo: "/assets/BrandImages/FK.png", alt: "FK" },
  { logo: "/assets/BrandImages/FKD.png", alt: "FKD" },
  { logo: "/assets/BrandImages/FKL.png", alt: "FKL" },
  { logo: "/assets/BrandImages/FLI.png", alt: "FLI" },
  { logo: "/assets/BrandImages/FLT.png", alt: "FLT" },
  { logo: "/assets/BrandImages/FLURO.png", alt: "FLURO" },
  { logo: "/assets/BrandImages/FREUDENBERG.png", alt: "FREUDENBERG" },
  { logo: "/assets/BrandImages/FUJI.png", alt: "FUJI" },
  { logo: "/assets/BrandImages/FYH.png", alt: "FYH" },
  { logo: "/assets/BrandImages/GATES.png", alt: "GATES" },
  { logo: "/assets/BrandImages/GAZPROMNEFT.png", alt: "GAZPROMNEFT" },
  { logo: "/assets/BrandImages/GAZPROMNEFT.png", alt: "GRANIT" },
  { logo: "/assets/BrandImages/GMB.png", alt: "GMB" },
  { logo: "/assets/BrandImages/GMN.png", alt: "GMN" },
  { logo: "/assets/BrandImages/HENKEL.png", alt: "HENKEL" },
  { logo: "/assets/BrandImages/HIMPT.png", alt: "HIMPT" },
  { logo: "/assets/BrandImages/HITACHI.png", alt: "HITACHI" },
  { logo: "/assets/BrandImages/HIWIN.png", alt: "HIWIN" },
  { logo: "/assets/BrandImages/HOFFMANN BEARINGS.png", alt: "HOFFMANN BEARINGS" },
  { logo: "/assets/BrandImages/HYMA.png", alt: "HYMA" },
  { logo: "/assets/BrandImages/IBB.png", alt: "IBB" },
  { logo: "/assets/BrandImages/IEFELE.png", alt: "EFELE" },
  { logo: "/assets/BrandImages/IGUS.png", alt: "IGUS" },
  { logo: "/assets/BrandImages/IJK.png", alt: "IJK" },
  { logo: "/assets/BrandImages/IKO.png", alt: "IKO" },
  { logo: "/assets/BrandImages/ILJIN.png", alt: "ILJIN" },
  { logo: "/assets/BrandImages/INA.png", alt: "INA" },
  { logo: "/assets/BrandImages/ISB.png", alt: "ISB" },
  { logo: "/assets/BrandImages/ISKRA.png", alt: "ISKRA" },
  { logo: "/assets/BrandImages/ITJ BEARINGS.png", alt: "ITJ BEARINGS" },
  { logo: "/assets/BrandImages/ITN BEARING.png", alt: "ITN BEARINGS" },
  { logo: "/assets/BrandImages/JED BEARINGS.png", alt: "JED" },
  { logo: "/assets/BrandImages/JIPE.png", alt: "JIPE" },
  { logo: "/assets/BrandImages/JNS.png", alt: "JNS" },
  { logo: "/assets/BrandImages/JTEKT.png", alt: "JTEKT KOYO" },
  { logo: "/assets/BrandImages/JVB.png", alt: "JVB" },
  { logo: "/assets/BrandImages/KBS LLC.png", alt: "KBS LLC" },
  { logo: "/assets/BrandImages/KG.png", alt: "KG" },
  { logo: "/assets/BrandImages/KMR.png", alt: "KMR" },
  { logo: "/assets/BrandImages/KOFK.png", alt: "KOFK" },
  { logo: "/assets/BrandImages/KSM.png", alt: "KSM" },
  { logo: "/assets/BrandImages/LDI.png", alt: "LDI" },
  { logo: "/assets/BrandImages/LDK BEARINGS.png", alt: "LDK BEARINGS" },
  { logo: "/assets/BrandImages/LFD.png", alt: "LFD" },
  { logo: "/assets/BrandImages/LINK-BELT.png", alt: "LINK-BELT" },
  { logo: "/assets/BrandImages/LK.png", alt: "LK" },
  { logo: "/assets/BrandImages/LOCTITE.png", alt: "LOCTITE" },
  { logo: "/assets/BrandImages/LOXEAL.jpg", alt: "LOXEAL" },
  { logo: "/assets/BrandImages/LPZ.png", alt: "LPZ" },
  { logo: "/assets/BrandImages/LS.png", alt: "LS" },
  { logo: "/assets/BrandImages/LYC.png", alt: "LYC" },
  { logo: "/assets/BrandImages/MANEUROP.jpg", alt: "MANEUROP" },
  { logo: "/assets/BrandImages/MANNOL.png", alt: "MANNOL" },
  { logo: "/assets/BrandImages/MAXCUT.png", alt: "MAXCUT" },
  { logo: "/assets/BrandImages/MAYR.png", alt: "MAYR" },
  { logo: "/assets/BrandImages/MBY.png", alt: "MBY" },
  { logo: "/assets/BrandImages/MK.png", alt: "MK" },
  { logo: "/assets/BrandImages/MOBIL.png", alt: "MOBIL" },
  { logo: "/assets/BrandImages/MOL.jpg", alt: "MOL" },
  { logo: "/assets/BrandImages/MOLYKOTE.png", alt: "MOLYKOTE" },
  { logo: "/assets/BrandImages/MPZ.png", alt: "MPZ" },
  { logo: "/assets/BrandImages/MRC.png", alt: "MRC" },
  { logo: "/assets/BrandImages/MTM BEARINGS.png", alt: "MTM BEARINGS" },
  { logo: "/assets/BrandImages/NACHI.png", alt: "NACHI" },
  { logo: "/assets/BrandImages/NADELLA.png", alt: "NADELLA" },
  { logo: "/assets/BrandImages/NAK.png", alt: "NAK" },
  { logo: "/assets/BrandImages/NANO.png", alt: "NANO" },
  { logo: "/assets/BrandImages/NB.png", alt: "NB" },
  { logo: "/assets/BrandImages/NBS.png", alt: "NBS" },
  { logo: "/assets/BrandImages/NECTECH.png", alt: "NECTECH" },
  { logo: "/assets/BrandImages/NEUTRAL.png", alt: "NEUTRAL" },
  { logo: "/assets/BrandImages/NIS RHINO.png", alt: "NIS RHINO" },
  { logo: "/assets/BrandImages/NIS.jpg", alt: "NIS" },
  { logo: "/assets/BrandImages/NITEK.png", alt: "NITEK" },
  { logo: "/assets/BrandImages/NKE BEARINGS.png", alt: "NKE BEARINGS" },
  { logo: "/assets/BrandImages/NKE.png", alt: "NKE" },
  { logo: "/assets/BrandImages/NMB.png", alt: "NMB" },
  { logo: "/assets/BrandImages/NOK.png", alt: "NOK" },
  { logo: "/assets/BrandImages/NORD.png", alt: "NORD" },
  { logo: "/assets/BrandImages/NPZ.png", alt: "NPZ" },
  { logo: "/assets/BrandImages/NSK.png", alt: "NSK" },
  { logo: "/assets/BrandImages/NTE.png", alt: "NTE" },
  { logo: "/assets/BrandImages/NTL.png", alt: "NTL" },
  { logo: "/assets/BrandImages/NTN.png", alt: "NTN" },
  { logo: "/assets/BrandImages/NXZ.png", alt: "NXZ" },
  { logo: "/assets/BrandImages/OID.png", alt: "OID" },
  { logo: "/assets/BrandImages/OILRIGHT.png", alt: "OILRIGHT" },
  { logo: "/assets/BrandImages/OPTIBELT.png", alt: "OPTIBELT" },
  { logo: "/assets/BrandImages/PATRIOT.jpg", alt: "PATRIOT" },
  { logo: "/assets/BrandImages/PEER BEARING.png", alt: "PEER BEARING" },
  { logo: "/assets/BrandImages/PETROPUMP.jpg", alt: "PETROPUMP" },
  { logo: "/assets/BrandImages/PIJ.png", alt: "PIJ" },
  { logo: "/assets/BrandImages/PIZZIRANI.png", alt: "PIZZIRANI" },
  { logo: "/assets/BrandImages/PMI.png", alt: "PMI" },
  { logo: "/assets/BrandImages/PODTRADE NEUTRAL.png", alt: "PODTRADE NEUTRAL" },
  { logo: "/assets/BrandImages/POWER STEER.jpg", alt: "POWER STEER" },
  { logo: "/assets/BrandImages/PTI.png", alt: "PTI" },
  { logo: "/assets/BrandImages/QIBR BEARINGS.png", alt: "QIBR BEARINGS" },
  { logo: "/assets/BrandImages/RDC.png", alt: "RDC" },
  { logo: "/assets/BrandImages/REGINA.png", alt: "REGINA" },
  { logo: "/assets/BrandImages/RENOLD.png", alt: "RENOLD" },
  { logo: "/assets/BrandImages/RGZ.png", alt: "RGZ" },
  { logo: "/assets/BrandImages/RHP.png", alt: "RHP" },
  { logo: "/assets/BrandImages/RINGSPANN.png", alt: "RINGSPANN" },
  { logo: "/assets/BrandImages/ROCKFORCE.png", alt: "ROCKFORCE" },
  { logo: "/assets/BrandImages/ROLLON.png", alt: "ROLLON" },
  { logo: "/assets/BrandImages/ROSLOCK.png", alt: "ROSLOCK" },
  { logo: "/assets/BrandImages/ROSPOD.jpg", alt: "ROSPOD" },
  { logo: "/assets/BrandImages/RUBENA.jpg", alt: "RUBENA" },
  { logo: "/assets/BrandImages/SAMICK.jpg", alt: "SAMICK" },
  { logo: "/assets/BrandImages/SANLUX.jpg", alt: "SANLUX" },
  { logo: "/assets/BrandImages/SATI.png", alt: "SATI" },
  { logo: "/assets/BrandImages/SBC.png", alt: "SBC" },
  { logo: "/assets/BrandImages/SCHAEFFLER FAG.png", alt: "SCHAEFFLER FAG" },
  { logo: "/assets/BrandImages/SCHNEEBERGER.png", alt: "SCHNEEBERGER" },
  { logo: "/assets/BrandImages/SECOP.png", alt: "SECOP" },
  { logo: "/assets/BrandImages/Permatex.jpg", alt: "Permatex" },
  { logo: "/assets/BrandImages/Podtrade.png", alt: "Podtrade" },
  { logo: "/assets/BrandImages/REXROTH.png", alt: "REXROTH" },
  { logo: "/assets/BrandImages/SIT.png", alt: "SIT" },
  { logo: "/assets/BrandImages/SKF.png", alt: "SKF" },
  { logo: "/assets/BrandImages/SLC.png", alt: "SLC" },
  { logo: "/assets/BrandImages/SLZ.jpg", alt: "SLZ" },
  { logo: "/assets/BrandImages/SMAZKA RU.png", alt: "SMAZKA RU" },
  { logo: "/assets/BrandImages/SMB BEARINGS.png", alt: "SMB BEARINGS" },
  { logo: "/assets/BrandImages/SNB LINEAR.png", alt: "SNB LINEAR" },
  { logo: "/assets/BrandImages/SNR.png", alt: "SNR" },
  { logo: "/assets/BrandImages/SPARTA.png", alt: "SPARTA" },
  { logo: "/assets/BrandImages/STAF.png", alt: "STAF" },
  { logo: "/assets/BrandImages/STANLEY FATMAX.png", alt: "STANLEY FATMAX" },
  { logo: "/assets/BrandImages/KURSK BEARING COMPANY.jpg", alt: "KURSK BEARING COMPANY" },
  { logo: "/assets/BrandImages/STC.png", alt: "STC" },
  { logo: "/assets/BrandImages/SXM.png", alt: "SXM" },
  { logo: "/assets/BrandImages/SYBR.png", alt: "SYBR" },
  { logo: "/assets/BrandImages/TBI.png", alt: "TBI" },
  { logo: "/assets/BrandImages/TECHNIX.png", alt: "TECHNIX" },
  { logo: "/assets/BrandImages/TEROSON.png", alt: "TEROSON" },
  { logo: "/assets/BrandImages/TFN.png", alt: "TFN" },
  { logo: "/assets/BrandImages/THK.png", alt: "THK" },
  { logo: "/assets/BrandImages/TIMKEN.png", alt: "TIMKEN" },
  { logo: "/assets/BrandImages/TOPTUL.png", alt: "TOPTUL" },
  { logo: "/assets/BrandImages/TORQUE.png", alt: "TORQUE" },
  { logo: "/assets/BrandImages/TSUBAKI.png", alt: "TSUBAKI" },
  { logo: "/assets/BrandImages/UBC.png", alt: "UBC" },
];

const BrandScroll = () => {
  return (
    <div className="relative mt-[86px] overflow-hidden md:mt-[140px] flex flex-col items-center justify-start gap-10 md:gap-20 brand-scroll">
      <div className="relative text-xl md:text-4xl font-semibold text-center">
        Global brands we work with
      </div>
      <div className="overflow-hidden whitespace-nowrap">
        <BrandLogoCards />
        <BrandLogoCards />
        <BrandLogoCards />
      </div>
    </div>
  );
};

export default BrandScroll;

const BrandLogoCards = () => {
  return (
    <div className="inline-block gap-[0px_100px] animate-[slider_120s_infinite_linear] items-center logo-container brand-scroll-child">
      {BrandLogo.map((item, index) => {
        return (
          <img
            className="relative object-contain w-32 h-20 ml-24 inline-block"
            alt={item.alt}
            src={item.logo}
            key={index}
          />
        );
      })}
    </div>
  );
};
